name: Release Klyx

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Generate changelog
        id: changelog
        run: |
          echo "## Changelog" > RELEASE_NOTES.md

          PREV_TAG=$(git tag --sort=-creatordate | grep -v "^${{ github.ref_name }}$" | head -n 1)
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, using initial commit"
            RANGE=""
          else
            echo "Previous tag found: $PREV_TAG"
            RANGE="$PREV_TAG..HEAD"
          fi

          git log $RANGE --pretty=format:"%s" |
          grep -E "^(feat|fix|perf|refactor|style|docs|test|chore)(\(.+\))?: " >> RELEASE_NOTES.md || echo "No valid commits."

          {
            echo "RELEASE_NOTES<<EOF"
            cat RELEASE_NOTES.md
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.KLYX_RELEASE }}

      - name: Rename APKs
        run: |
          mkdir -p renamed-apks
          cp build/outputs/apk/debug/app-debug.apk renamed-apks/klyx-debug-${{ github.ref_name }}.apk
          cp build/outputs/apk/release/app-release.apk renamed-apks/klyx-release-${{ github.ref_name }}.apk

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
            build/outputs/**/*.apk
